
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.schema_migrations (
    version INTEGER PRIMARY KEY,
    applied_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    duration_minutes INTEGER NOT NULL CHECK (duration_minutes BETWEEN 1 AND 1440),
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1))
);
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.masters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1))
);
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1))
);
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.master_services (
    master_id BIGINT NOT NULL REFERENCES __APP_SCHEMA__.masters(id),
    service_id BIGINT NOT NULL REFERENCES __APP_SCHEMA__.services(id),
    PRIMARY KEY (master_id, service_id)
);
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.room_services (
    room_id BIGINT NOT NULL REFERENCES __APP_SCHEMA__.rooms(id),
    service_id BIGINT NOT NULL REFERENCES __APP_SCHEMA__.services(id),
    PRIMARY KEY (room_id, service_id)
);

-- weekday: Monday=0. Date-specific open intervals replace weekly opens for that date.
-- Date-specific closed intervals always subtract from opens.
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.work_intervals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_id BIGINT REFERENCES __APP_SCHEMA__.masters(id),
    room_id BIGINT REFERENCES __APP_SCHEMA__.rooms(id),
    weekday INTEGER CHECK (weekday BETWEEN 0 AND 6),
    local_date TEXT,
    mode TEXT NOT NULL CHECK (mode IN ('open', 'closed')),
    start_minute INTEGER NOT NULL CHECK (start_minute BETWEEN 0 AND 1439),
    end_minute INTEGER NOT NULL CHECK (end_minute BETWEEN 1 AND 1440),
    CHECK ((master_id IS NOT NULL) != (room_id IS NOT NULL)),
    CHECK ((weekday IS NOT NULL) != (local_date IS NOT NULL)),
    CHECK (start_minute < end_minute)
);
CREATE INDEX IF NOT EXISTS work_master_day ON __APP_SCHEMA__.work_intervals(master_id, local_date, weekday);
CREATE INDEX IF NOT EXISTS work_room_day ON __APP_SCHEMA__.work_intervals(room_id, local_date, weekday);

CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.resource_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_id BIGINT REFERENCES __APP_SCHEMA__.masters(id),
    room_id BIGINT REFERENCES __APP_SCHEMA__.rooms(id),
    start_utc TEXT NOT NULL,
    end_utc TEXT NOT NULL,
    reason TEXT,
    created_by TEXT NOT NULL,
    CHECK ((master_id IS NOT NULL) != (room_id IS NOT NULL)),
    CHECK (start_utc < end_utc)
);
CREATE INDEX IF NOT EXISTS blocks_master_time ON __APP_SCHEMA__.resource_blocks(master_id, start_utc, end_utc);
CREATE INDEX IF NOT EXISTS blocks_room_time ON __APP_SCHEMA__.resource_blocks(room_id, start_utc, end_utc);

CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vk_id BIGINT UNIQUE,
    phone TEXT NOT NULL,
    phone_provided_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT REFERENCES __APP_SCHEMA__.clients(id),
    service_id BIGINT NOT NULL REFERENCES __APP_SCHEMA__.services(id),
    master_id BIGINT NOT NULL REFERENCES __APP_SCHEMA__.masters(id),
    room_id BIGINT NOT NULL REFERENCES __APP_SCHEMA__.rooms(id),
    start_utc TEXT NOT NULL,
    end_utc TEXT NOT NULL,
    source TEXT NOT NULL CHECK (source IN ('vk', 'admin')),
    status TEXT NOT NULL CHECK (status IN ('confirmed', 'cancelled', 'rescheduled')),
    phone_snapshot TEXT NOT NULL,
    service_name_snapshot TEXT NOT NULL,
    master_name_snapshot TEXT NOT NULL,
    prior_booking_id BIGINT REFERENCES __APP_SCHEMA__.bookings(id),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CHECK (start_utc < end_utc)
);
CREATE INDEX IF NOT EXISTS bookings_master_time ON __APP_SCHEMA__.bookings(master_id, start_utc, end_utc) WHERE status='confirmed';
CREATE INDEX IF NOT EXISTS bookings_room_time ON __APP_SCHEMA__.bookings(room_id, start_utc, end_utc) WHERE status='confirmed';
CREATE INDEX IF NOT EXISTS bookings_client ON __APP_SCHEMA__.bookings(client_id, status, start_utc);

-- Second line of defense if a later consumer bypasses the booking service.
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.booking_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES __APP_SCHEMA__.bookings(id),
    event TEXT NOT NULL,
    actor TEXT NOT NULL,
    details_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.vk_dialogs (
    vk_id BIGINT PRIMARY KEY,
    state TEXT NOT NULL,
    draft_json TEXT NOT NULL,
    expires_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.inbound_events (
    event_id TEXT PRIMARY KEY,
    vk_id BIGINT,
    status TEXT NOT NULL,
    result_json TEXT,
    received_at TEXT NOT NULL,
    processed_at TEXT
);
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.action_results (
    action_key TEXT PRIMARY KEY,
    action_kind TEXT NOT NULL,
    fingerprint TEXT NOT NULL,
    booking_id BIGINT REFERENCES __APP_SCHEMA__.bookings(id),
    created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.message_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT REFERENCES __APP_SCHEMA__.bookings(id),
    recipient_vk_id BIGINT NOT NULL,
    event_kind TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'sent', 'failed', 'superseded')),
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    created_at TEXT NOT NULL,
    sent_at TEXT,
    UNIQUE(booking_id, event_kind)
);

CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.vk_outgoing_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inbound_event_id TEXT REFERENCES __APP_SCHEMA__.inbound_events(event_id),
    booking_id BIGINT REFERENCES __APP_SCHEMA__.bookings(id),
    event_kind TEXT,
    recipient_vk_id BIGINT NOT NULL,
    text TEXT NOT NULL,
    keyboard_json TEXT NOT NULL DEFAULT '[]',
    dedupe_key TEXT NOT NULL UNIQUE,
    random_id INTEGER NOT NULL UNIQUE,
    status TEXT NOT NULL CHECK (status IN ('pending', 'sent', 'failed', 'superseded')),
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    created_at TEXT NOT NULL,
    sent_at TEXT
);
CREATE INDEX IF NOT EXISTS vk_outbox_delivery ON __APP_SCHEMA__.vk_outgoing_messages(status, id);

-- M6 authentication is deliberately server-side. Passwords and raw session
-- tokens are never stored; role expansion is blocked until the salon approves
-- its staff model.
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    password_salt BYTEA NOT NULL,
    password_hash BYTEA NOT NULL,
    password_iterations INTEGER NOT NULL CHECK (password_iterations >= 100000),
    role TEXT NOT NULL DEFAULT 'admin' CHECK (role = 'admin'),
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    created_at TEXT NOT NULL,
    password_changed_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.admin_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT NOT NULL REFERENCES __APP_SCHEMA__.admin_users(id) ON DELETE CASCADE,
    token_hash BYTEA NOT NULL UNIQUE,
    created_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL,
    expires_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS admin_sessions_expiry ON __APP_SCHEMA__.admin_sessions(expires_at);

CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.admin_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor TEXT NOT NULL,
    action TEXT NOT NULL,
    object_type TEXT NOT NULL,
    object_id TEXT,
    details_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS admin_audit_recent ON __APP_SCHEMA__.admin_audit_log(created_at, id);

-- Direct consumers must share the same lock as the booking service. The trigger
-- serializes even a writer that bypasses the service and rejects overlaps.
CREATE OR REPLACE FUNCTION __APP_SCHEMA__.protect_booking_overlap() RETURNS trigger LANGUAGE plpgsql SET search_path = pg_catalog, __APP_SCHEMA__ AS $$
BEGIN
    IF NEW.status = 'confirmed' THEN
        PERFORM pg_advisory_xact_lock(706547229101);
        IF EXISTS (
            SELECT 1 FROM __APP_SCHEMA__.bookings b
            WHERE b.status = 'confirmed' AND b.id IS DISTINCT FROM NEW.id
              AND b.start_utc < NEW.end_utc AND b.end_utc > NEW.start_utc
              AND (b.master_id = NEW.master_id OR b.room_id = NEW.room_id
                   OR (NEW.client_id IS NOT NULL AND b.client_id = NEW.client_id)
                   OR b.phone_snapshot = NEW.phone_snapshot)
        ) THEN
            RAISE EXCEPTION 'booking overlap' USING ERRCODE = '23505';
        END IF;
    END IF;
    RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS booking_overlap_guard ON __APP_SCHEMA__.bookings;
CREATE TRIGGER booking_overlap_guard BEFORE INSERT OR UPDATE OF master_id,room_id,client_id,
    phone_snapshot,start_utc,end_utc,status ON __APP_SCHEMA__.bookings
    FOR EACH ROW EXECUTE FUNCTION __APP_SCHEMA__.protect_booking_overlap();
CREATE UNIQUE INDEX IF NOT EXISTS one_active_admin ON __APP_SCHEMA__.admin_users(active) WHERE active=1;
CREATE UNIQUE INDEX IF NOT EXISTS admin_username_ci ON __APP_SCHEMA__.admin_users(lower(username));
