-- Migration 4. The Python upgrader owns backfill/order; this file installs
-- canonical storage and its invariants. No extension or new database is needed.
CREATE OR REPLACE FUNCTION __APP_SCHEMA__.current_salon_id() RETURNS bigint
LANGUAGE sql STABLE SET search_path = pg_catalog AS $$
 SELECT CASE WHEN current_setting('app.salon_id', true) ~ '^[1-9][0-9]{0,17}$'
             THEN current_setting('app.salon_id', true)::bigint ELSE NULL END
$$;

CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.salons (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name text NOT NULL,
 active integer NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
 entity_id bigint UNIQUE
);
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.salon_memberships (
 salon_id bigint NOT NULL REFERENCES __APP_SCHEMA__.salons(id),
 user_id bigint NOT NULL REFERENCES __APP_SCHEMA__.accounts(id),
 role text NOT NULL DEFAULT 'admin' CHECK(role='admin'),
 active integer NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
 PRIMARY KEY(salon_id,user_id)
);
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.shared_masters (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
 CHECK(id > 0 AND id < 9223372036854775807)
);
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.entity_types (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 salon_id bigint NOT NULL DEFAULT __APP_SCHEMA__.current_salon_id() REFERENCES __APP_SCHEMA__.salons(id),
 code text NOT NULL CHECK(code ~ '^[a-z][a-z0-9_]{0,63}$'),
 label text NOT NULL CHECK(length(btrim(label)) BETWEEN 1 AND 200),
 core boolean NOT NULL DEFAULT false,
 projection_table text,
 version bigint NOT NULL DEFAULT 1 CHECK(version>0),
 UNIQUE(salon_id,id), UNIQUE(salon_id,code),
 CHECK(core OR projection_table IS NULL)
);
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.entities (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 salon_id bigint NOT NULL DEFAULT __APP_SCHEMA__.current_salon_id() REFERENCES __APP_SCHEMA__.salons(id),
 entity_type_id bigint NOT NULL,
 projection_key jsonb,
 archived boolean NOT NULL DEFAULT false,
 version bigint NOT NULL DEFAULT 1 CHECK(version>0),
 UNIQUE(salon_id,id), UNIQUE(salon_id,id,entity_type_id),
 UNIQUE(salon_id,entity_type_id,projection_key),
 FOREIGN KEY(salon_id,entity_type_id) REFERENCES __APP_SCHEMA__.entity_types(salon_id,id)
);
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.entity_parameters (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 salon_id bigint NOT NULL DEFAULT __APP_SCHEMA__.current_salon_id() REFERENCES __APP_SCHEMA__.salons(id),
 entity_type_id bigint NOT NULL,
 code text NOT NULL CHECK(code ~ '^[a-z][a-z0-9_]{0,63}$'),
 label text NOT NULL CHECK(length(btrim(label)) BETWEEN 1 AND 200),
 data_type text NOT NULL CHECK(data_type IN ('string','integer','number','boolean','date','reference')),
 required boolean NOT NULL DEFAULT false,
 core boolean NOT NULL DEFAULT false,
 reference_type_id bigint,
 reference_key text NOT NULL DEFAULT 'id',
 version bigint NOT NULL DEFAULT 1 CHECK(version>0),
 UNIQUE(salon_id,id), UNIQUE(salon_id,id,entity_type_id),
 UNIQUE(salon_id,entity_type_id,code),
 FOREIGN KEY(salon_id,entity_type_id) REFERENCES __APP_SCHEMA__.entity_types(salon_id,id),
 FOREIGN KEY(salon_id,reference_type_id) REFERENCES __APP_SCHEMA__.entity_types(salon_id,id),
 CHECK((data_type='reference') = (reference_type_id IS NOT NULL))
);
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.entity_parameter_values (
 salon_id bigint NOT NULL DEFAULT __APP_SCHEMA__.current_salon_id(),
 entity_id bigint NOT NULL,
 parameter_id bigint NOT NULL,
 entity_type_id bigint NOT NULL,
 value_string text,
 value_integer bigint,
 value_number numeric,
 value_boolean boolean,
 value_date date,
 value_reference bigint,
 PRIMARY KEY(salon_id,entity_id,parameter_id),
 FOREIGN KEY(salon_id,entity_id,entity_type_id)
  REFERENCES __APP_SCHEMA__.entities(salon_id,id,entity_type_id) ON DELETE CASCADE,
 FOREIGN KEY(salon_id,parameter_id,entity_type_id)
  REFERENCES __APP_SCHEMA__.entity_parameters(salon_id,id,entity_type_id),
 FOREIGN KEY(salon_id,value_reference) REFERENCES __APP_SCHEMA__.entities(salon_id,id),
 CHECK(num_nonnulls(value_string,value_integer,value_number,value_boolean,value_date,value_reference)=1),
 CHECK(value_number IS NULL OR value_number NOT IN ('NaN'::numeric,'Infinity'::numeric,'-Infinity'::numeric))
);
CREATE INDEX IF NOT EXISTS entities_type ON __APP_SCHEMA__.entities(salon_id,entity_type_id,id);
CREATE INDEX IF NOT EXISTS entity_values_reference ON __APP_SCHEMA__.entity_parameter_values(salon_id,value_reference)
 WHERE value_reference IS NOT NULL;

CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.shared_master_busy (
 booking_id bigint PRIMARY KEY REFERENCES __APP_SCHEMA__.bookings(id) ON DELETE CASCADE,
 shared_master_id bigint NOT NULL REFERENCES __APP_SCHEMA__.shared_masters(id),
 start_utc timestamptz NOT NULL,
 end_utc timestamptz NOT NULL,
 CHECK(start_utc<end_utc),
 EXCLUDE USING gist (
  int8range(shared_master_id,shared_master_id,'[]') WITH &&,
  tstzrange(start_utc,end_utc,'[)') WITH &&
 )
);
REVOKE ALL ON __APP_SCHEMA__.shared_master_busy FROM PUBLIC;
REVOKE ALL ON __APP_SCHEMA__.shared_masters FROM PUBLIC;

CREATE OR REPLACE FUNCTION __APP_SCHEMA__.guard_metadata() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, __APP_SCHEMA__ AS $$
DECLARE old_row jsonb; new_row jsonb; type_id bigint; sid bigint; type_core boolean;
BEGIN
 IF TG_OP<>'INSERT' THEN
  old_row:=to_jsonb(OLD);
  IF TG_OP='UPDATE' AND pg_trigger_depth()>1 AND
      (to_jsonb(NEW)-'version')=(old_row-'version') THEN RETURN NEW; END IF;
  IF OLD.core THEN RAISE EXCEPTION 'Core metadata is immutable' USING ERRCODE='23514'; END IF;
 END IF;
 IF TG_OP<>'DELETE' THEN
  new_row:=to_jsonb(NEW);
  IF (NEW.core AND pg_trigger_depth()=1) OR (TG_OP='UPDATE' AND (NEW.id<>OLD.id OR NEW.salon_id<>OLD.salon_id
      OR NEW.code<>OLD.code)) THEN
   RAISE EXCEPTION 'Metadata identity/core flags are immutable' USING ERRCODE='23514';
  END IF;
  IF TG_OP='UPDATE' THEN NEW.version:=OLD.version+1; END IF;
 END IF;
 IF TG_TABLE_NAME='entity_parameters' THEN
  type_id:=COALESCE((new_row->>'entity_type_id')::bigint,(old_row->>'entity_type_id')::bigint);
  sid:=COALESCE((new_row->>'salon_id')::bigint,(old_row->>'salon_id')::bigint);
  SELECT core INTO STRICT type_core FROM __APP_SCHEMA__.entity_types WHERE salon_id=sid AND id=type_id FOR UPDATE;
  IF TG_OP<>'DELETE' AND type_core AND NEW.required AND NOT NEW.core THEN
   RAISE EXCEPTION 'Additional core parameters must be optional' USING ERRCODE='23514';
  END IF;
  IF TG_OP='UPDATE' AND NEW.entity_type_id<>OLD.entity_type_id THEN
   RAISE EXCEPTION 'Parameter ownership is immutable' USING ERRCODE='23514';
  END IF;
  IF TG_OP='DELETE' OR (TG_OP='UPDATE' AND
    (NEW.data_type<>OLD.data_type OR NEW.reference_type_id IS DISTINCT FROM OLD.reference_type_id)) THEN
   IF EXISTS(SELECT 1 FROM __APP_SCHEMA__.entity_parameter_values WHERE salon_id=sid AND parameter_id=OLD.id) THEN
    RAISE EXCEPTION 'Populated parameter cannot be removed or retyped' USING ERRCODE='23514';
   END IF;
  END IF;
  IF TG_OP<>'DELETE' AND NEW.required AND (TG_OP='INSERT' OR NOT OLD.required) AND EXISTS(
   SELECT 1 FROM __APP_SCHEMA__.entities e WHERE e.salon_id=sid AND e.entity_type_id=type_id AND NOT e.archived
    AND NOT EXISTS(SELECT 1 FROM __APP_SCHEMA__.entity_parameter_values v WHERE v.salon_id=sid
       AND v.entity_id=e.id AND v.parameter_id=NEW.id)) THEN
   RAISE EXCEPTION 'Required parameter needs a value on every existing entity' USING ERRCODE='23514';
  END IF;
  UPDATE __APP_SCHEMA__.entity_types SET version=version+1 WHERE salon_id=sid AND id=type_id;
 END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF;
 RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION __APP_SCHEMA__.guard_entity() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, __APP_SCHEMA__ AS $$
DECLARE typ __APP_SCHEMA__.entity_types;
BEGIN
 SELECT * INTO STRICT typ FROM __APP_SCHEMA__.entity_types WHERE salon_id=COALESCE(NEW.salon_id,OLD.salon_id)
   AND id=COALESCE(NEW.entity_type_id,OLD.entity_type_id) FOR UPDATE;
 IF pg_trigger_depth()=1 AND typ.core THEN
  RAISE EXCEPTION 'Core entities are changed by their service API' USING ERRCODE='23514';
 END IF;
 IF TG_OP='UPDATE' AND (NEW.id<>OLD.id OR NEW.salon_id<>OLD.salon_id
     OR NEW.entity_type_id<>OLD.entity_type_id OR NEW.projection_key IS DISTINCT FROM OLD.projection_key) THEN
  RAISE EXCEPTION 'Entity identity is immutable' USING ERRCODE='23514';
 END IF;
 IF TG_OP='UPDATE' AND NEW.archived AND NOT OLD.archived AND EXISTS(
  SELECT 1 FROM __APP_SCHEMA__.entity_parameter_values v JOIN __APP_SCHEMA__.entities e
   ON e.salon_id=v.salon_id AND e.id=v.entity_id
  WHERE v.salon_id=NEW.salon_id AND v.value_reference=NEW.id AND NOT e.archived) THEN
  RAISE EXCEPTION 'Entity is referenced by an active object' USING ERRCODE='23514';
 END IF;
 IF TG_OP<>'DELETE' AND NOT typ.core AND NEW.projection_key IS NOT NULL THEN
  RAISE EXCEPTION 'Custom entities cannot claim a core projection' USING ERRCODE='23514';
 END IF;
 IF TG_OP='UPDATE' THEN NEW.version:=OLD.version+1; END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF;
 RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION __APP_SCHEMA__.guard_entity_value() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, __APP_SCHEMA__ AS $$
DECLARE p __APP_SCHEMA__.entity_parameters; e __APP_SCHEMA__.entities; ref_type bigint;
BEGIN
 SELECT * INTO STRICT p FROM __APP_SCHEMA__.entity_parameters
 WHERE salon_id=COALESCE(NEW.salon_id,OLD.salon_id) AND id=COALESCE(NEW.parameter_id,OLD.parameter_id) FOR SHARE;
 PERFORM 1 FROM __APP_SCHEMA__.entity_types WHERE salon_id=p.salon_id AND id=p.entity_type_id FOR UPDATE;
 IF pg_trigger_depth()=1 AND p.core AND NOT (
   TG_OP='UPDATE' AND p.code='name'
   AND COALESCE(current_setting('app.salon_profile_write',true),'')='on'
   AND __APP_SCHEMA__.current_salon_id()=p.salon_id
   AND EXISTS(SELECT 1 FROM __APP_SCHEMA__.entity_types
     WHERE salon_id=p.salon_id AND id=p.entity_type_id AND code='salon_settings')
 ) THEN
  RAISE EXCEPTION 'Core values are changed by their service API' USING ERRCODE='23514';
 END IF;
 IF TG_OP='DELETE' THEN
  -- A cascading delete runs after its parent entity has been removed.
  PERFORM 1 FROM __APP_SCHEMA__.entities WHERE salon_id=p.salon_id AND id=OLD.entity_id FOR UPDATE;
  RETURN OLD;
 END IF;
 SELECT * INTO STRICT e FROM __APP_SCHEMA__.entities WHERE salon_id=p.salon_id
   AND id=NEW.entity_id FOR UPDATE;
 IF TG_OP='UPDATE' AND (NEW.salon_id<>OLD.salon_id OR NEW.entity_id<>OLD.entity_id
    OR NEW.parameter_id<>OLD.parameter_id OR NEW.entity_type_id<>OLD.entity_type_id) THEN
  RAISE EXCEPTION 'Value identity is immutable' USING ERRCODE='23514';
 END IF;
 IF e.archived OR NEW.entity_type_id<>p.entity_type_id OR e.entity_type_id<>p.entity_type_id THEN
  RAISE EXCEPTION 'Invalid entity/parameter ownership' USING ERRCODE='23514';
 END IF;
 IF (p.data_type='string' AND NEW.value_string IS NULL)
 OR (p.data_type='integer' AND NEW.value_integer IS NULL)
 OR (p.data_type='number' AND NEW.value_number IS NULL)
 OR (p.data_type='boolean' AND NEW.value_boolean IS NULL)
 OR (p.data_type='date' AND NEW.value_date IS NULL)
 OR (p.data_type='reference' AND NEW.value_reference IS NULL) THEN
  RAISE EXCEPTION 'Value does not match parameter type' USING ERRCODE='23514';
 END IF;
 IF p.data_type='reference' THEN
  SELECT entity_type_id INTO ref_type FROM __APP_SCHEMA__.entities
    WHERE salon_id=NEW.salon_id AND id=NEW.value_reference AND NOT archived FOR SHARE;
  IF ref_type IS DISTINCT FROM p.reference_type_id THEN
   RAISE EXCEPTION 'Reference must point to an active entity of its declared type in the same salon'
    USING ERRCODE='23514';
  END IF;
 END IF;
 RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION __APP_SCHEMA__.check_required_entity_values() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, __APP_SCHEMA__ AS $$
DECLARE eid bigint; sid bigint; typ bigint; previous_scope text;
BEGIN
 eid:=COALESCE((to_jsonb(NEW)->>'entity_id')::bigint,(to_jsonb(OLD)->>'entity_id')::bigint,
              (to_jsonb(NEW)->>'id')::bigint,(to_jsonb(OLD)->>'id')::bigint);
 sid:=COALESCE(NEW.salon_id,OLD.salon_id);
 previous_scope:=current_setting('app.salon_id',true);
 PERFORM set_config('app.salon_id',sid::text,true);
 SELECT entity_type_id INTO typ FROM __APP_SCHEMA__.entities WHERE salon_id=sid AND id=eid AND NOT archived;
 IF FOUND AND EXISTS(SELECT 1 FROM __APP_SCHEMA__.entity_parameters p WHERE p.salon_id=sid
  AND p.entity_type_id=typ AND p.required AND NOT EXISTS(
   SELECT 1 FROM __APP_SCHEMA__.entity_parameter_values v WHERE v.salon_id=sid
     AND v.entity_id=eid AND v.parameter_id=p.id)) THEN
  RAISE EXCEPTION 'Missing required entity parameter' USING ERRCODE='23514';
 END IF;
 PERFORM set_config('app.salon_id',COALESCE(previous_scope,''),true);
 RETURN NULL;
END $$;

-- Compatibility writes are commands: both projection and canonical values
-- change in the same transaction. Direct canonical core writes are rejected.
CREATE OR REPLACE FUNCTION __APP_SCHEMA__.projection_entity_before() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, __APP_SCHEMA__ AS $$
DECLARE typ bigint; key jsonb := '{}'::jsonb; column_name text;
BEGIN
 IF TG_OP='UPDATE' THEN
  IF NEW.salon_id<>OLD.salon_id OR NEW.entity_id IS DISTINCT FROM OLD.entity_id THEN
   RAISE EXCEPTION 'Projection ownership is immutable' USING ERRCODE='23514';
  END IF;
  FOREACH column_name IN ARRAY string_to_array(TG_ARGV[1],',') LOOP
   IF to_jsonb(NEW)->column_name IS DISTINCT FROM to_jsonb(OLD)->column_name THEN
    RAISE EXCEPTION 'Projection identity is immutable' USING ERRCODE='23514';
   END IF;
  END LOOP;
  IF TG_TABLE_NAME='masters' AND (to_jsonb(NEW)->'shared_master_id') IS DISTINCT FROM (to_jsonb(OLD)->'shared_master_id') THEN
   RAISE EXCEPTION 'Shared master identity is immutable; attach a new salon profile' USING ERRCODE='23514';
  END IF;
  RETURN NEW;
 END IF;
 SELECT id INTO STRICT typ FROM __APP_SCHEMA__.entity_types WHERE salon_id=NEW.salon_id AND code=TG_ARGV[0];
 FOREACH column_name IN ARRAY string_to_array(TG_ARGV[1],',') LOOP
  key:=key || jsonb_build_object(column_name,to_jsonb(NEW)->column_name);
 END LOOP;
 IF NEW.entity_id IS NOT NULL THEN
  RAISE EXCEPTION 'Projection entity identity is assigned internally' USING ERRCODE='23514';
 END IF;
 INSERT INTO __APP_SCHEMA__.entities(salon_id,entity_type_id,projection_key) VALUES(NEW.salon_id,typ,key)
 ON CONFLICT(salon_id,entity_type_id,projection_key) DO UPDATE
  SET projection_key=excluded.projection_key
 RETURNING id INTO NEW.entity_id;
 IF TG_TABLE_NAME='masters' AND (to_jsonb(NEW)->>'shared_master_id') IS NULL THEN
  INSERT INTO __APP_SCHEMA__.shared_masters DEFAULT VALUES RETURNING id INTO NEW.shared_master_id;
 END IF;
 RETURN NEW;
END $$;

-- BEFORE INSERT also runs for candidates rejected by ON CONFLICT. A natural
-- projection key reuses its entity above; a generated-ID candidate can instead
-- conflict on another unique key. Remove its still-empty entity after the
-- actual projection INSERT/UPDATE has completed, before deferred required-value
-- checks. Established projections and entities with values are never removed.
CREATE OR REPLACE FUNCTION __APP_SCHEMA__.prune_ignored_projection_entities() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, __APP_SCHEMA__ AS $$
DECLARE sid bigint := __APP_SCHEMA__.current_salon_id(); typ bigint;
BEGIN
 IF sid IS NULL THEN RETURN NULL; END IF;
 SELECT id INTO STRICT typ FROM __APP_SCHEMA__.entity_types WHERE salon_id=sid AND code=TG_ARGV[0];
 EXECUTE format('DELETE FROM %I.entities e WHERE e.salon_id=$1 AND e.entity_type_id=$2
  AND NOT EXISTS(SELECT 1 FROM %I.%I p WHERE p.salon_id=e.salon_id AND p.entity_id=e.id)
  AND NOT EXISTS(SELECT 1 FROM %I.entity_parameter_values v WHERE v.salon_id=e.salon_id AND v.entity_id=e.id)',
  TG_TABLE_SCHEMA,TG_TABLE_SCHEMA,TG_TABLE_NAME,TG_TABLE_SCHEMA) USING sid,typ;
 RETURN NULL;
END $$;

-- Technical immutable bootstrap definitions contain schema/defaults, no client,
-- account or master data. Each new salon gets independent metadata IDs/versions.
CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.core_entity_templates (
 code text PRIMARY KEY,
 label text NOT NULL,
 projection_table text,
 parameters jsonb NOT NULL,
 defaults jsonb NOT NULL DEFAULT '{}'
);
REVOKE ALL ON __APP_SCHEMA__.core_entity_templates FROM PUBLIC;
REVOKE INSERT,UPDATE,DELETE ON __APP_SCHEMA__.salons FROM PUBLIC;

CREATE OR REPLACE FUNCTION __APP_SCHEMA__.initialize_salon_metadata() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, __APP_SCHEMA__ AS $$
DECLARE template record; param jsonb; typ bigint; ref_typ bigint; pid bigint; eid bigint;
 dtype text; val jsonb; policy jsonb; previous_scope text;
BEGIN
 previous_scope:=current_setting('app.salon_id',true);
 PERFORM set_config('app.salon_id',NEW.id::text,true);
 policy:=COALESCE(NULLIF(current_setting('app.provision_policy',true),'')::jsonb,'{}'::jsonb);
 FOR template IN SELECT * FROM __APP_SCHEMA__.core_entity_templates ORDER BY code LOOP
  INSERT INTO __APP_SCHEMA__.entity_types(salon_id,code,label,core,projection_table)
   VALUES(NEW.id,template.code,template.label,true,template.projection_table);
 END LOOP;
 FOR template IN SELECT * FROM __APP_SCHEMA__.core_entity_templates ORDER BY code LOOP
  SELECT id INTO STRICT typ FROM __APP_SCHEMA__.entity_types WHERE salon_id=NEW.id AND code=template.code;
  FOR param IN SELECT * FROM jsonb_array_elements(template.parameters) LOOP
   ref_typ:=NULL;
   IF param->>'reference_code' IS NOT NULL THEN
    SELECT id INTO STRICT ref_typ FROM __APP_SCHEMA__.entity_types WHERE salon_id=NEW.id AND code=param->>'reference_code';
   END IF;
   INSERT INTO __APP_SCHEMA__.entity_parameters(salon_id,entity_type_id,code,label,data_type,required,core,reference_type_id,reference_key)
   VALUES(NEW.id,typ,param->>'code',param->>'label',param->>'data_type',
    (param->>'required')::boolean,true,ref_typ,COALESCE(param->>'reference_key','id'));
  END LOOP;
  IF template.code='salon_settings' THEN
   INSERT INTO __APP_SCHEMA__.entities(salon_id,entity_type_id,projection_key)
    VALUES(NEW.id,typ,jsonb_build_object('id',NEW.id)) RETURNING id INTO eid;
   FOR param IN SELECT * FROM jsonb_array_elements(template.parameters) LOOP
    SELECT id,data_type INTO STRICT pid,dtype FROM __APP_SCHEMA__.entity_parameters
     WHERE salon_id=NEW.id AND entity_type_id=typ AND code=param->>'code';
    val:=COALESCE(policy->(param->>'code'),template.defaults->(param->>'code'));
    IF param->>'code'='name' THEN val:=to_jsonb(NEW.name); END IF;
    INSERT INTO __APP_SCHEMA__.entity_parameter_values(salon_id,entity_id,parameter_id,entity_type_id,
     value_string,value_integer,value_boolean)
    VALUES(NEW.id,eid,pid,typ,
     CASE WHEN dtype='string' THEN val#>>'{}' END,
     CASE WHEN dtype='integer' THEN (val#>>'{}')::bigint END,
     CASE WHEN dtype='boolean' THEN (val#>>'{}')::boolean END);
   END LOOP;
   UPDATE __APP_SCHEMA__.salons SET entity_id=eid WHERE id=NEW.id;
  END IF;
 END LOOP;
 PERFORM set_config('app.salon_id',COALESCE(previous_scope,''),true);
 RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION __APP_SCHEMA__.sync_projection_values() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, __APP_SCHEMA__ AS $$
DECLARE p __APP_SCHEMA__.entity_parameters; row_data jsonb; v jsonb; ref_id bigint;
BEGIN
 IF TG_OP='DELETE' THEN
  DELETE FROM __APP_SCHEMA__.entities WHERE salon_id=OLD.salon_id AND id=OLD.entity_id;
  RETURN OLD;
 END IF;
 row_data:=to_jsonb(NEW);
 FOR p IN SELECT * FROM __APP_SCHEMA__.entity_parameters WHERE salon_id=NEW.salon_id
  AND entity_type_id=(SELECT entity_type_id FROM __APP_SCHEMA__.entities WHERE salon_id=NEW.salon_id AND id=NEW.entity_id)
  AND core LOOP
  v:=row_data->p.code;
  IF v IS NULL OR v='null'::jsonb THEN
   DELETE FROM __APP_SCHEMA__.entity_parameter_values WHERE salon_id=NEW.salon_id AND entity_id=NEW.entity_id AND parameter_id=p.id;
  ELSE
   ref_id:=NULL;
   IF p.data_type='reference' THEN
    SELECT id INTO STRICT ref_id FROM __APP_SCHEMA__.entities WHERE salon_id=NEW.salon_id
     AND entity_type_id=p.reference_type_id AND projection_key=jsonb_build_object(p.reference_key,v);
   END IF;
   INSERT INTO __APP_SCHEMA__.entity_parameter_values(salon_id,entity_id,parameter_id,entity_type_id,
     value_string,value_integer,value_number,value_boolean,value_date,value_reference)
   VALUES(NEW.salon_id,NEW.entity_id,p.id,p.entity_type_id,
     CASE WHEN p.data_type='string' THEN v#>>'{}' END,
     CASE WHEN p.data_type='integer' THEN (v#>>'{}')::bigint END,
     CASE WHEN p.data_type='number' THEN (v#>>'{}')::numeric END,
     CASE WHEN p.data_type='boolean' THEN (v#>>'{}')::boolean END,
     CASE WHEN p.data_type='date' THEN (v#>>'{}')::date END,ref_id)
   ON CONFLICT(salon_id,entity_id,parameter_id) DO UPDATE SET
     value_string=excluded.value_string,value_integer=excluded.value_integer,
     value_number=excluded.value_number,value_boolean=excluded.value_boolean,
     value_date=excluded.value_date,value_reference=excluded.value_reference;
  END IF;
 END LOOP;
 UPDATE __APP_SCHEMA__.entities SET version=version+1 WHERE salon_id=NEW.salon_id AND id=NEW.entity_id;
 RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION __APP_SCHEMA__.bump_entity_value_version() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, __APP_SCHEMA__ AS $$
BEGIN
 UPDATE __APP_SCHEMA__.entities SET version=version+1
 WHERE salon_id=COALESCE(NEW.salon_id,OLD.salon_id)
   AND id=COALESCE(NEW.entity_id,OLD.entity_id);
 RETURN NULL;
END $$;

CREATE OR REPLACE FUNCTION __APP_SCHEMA__.sync_salon_name() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, __APP_SCHEMA__ AS $$
BEGIN
 IF NEW.value_string IS NOT NULL AND EXISTS(SELECT 1 FROM __APP_SCHEMA__.entity_parameters p
  JOIN __APP_SCHEMA__.entity_types t ON t.salon_id=p.salon_id AND t.id=p.entity_type_id
  WHERE p.salon_id=NEW.salon_id AND p.id=NEW.parameter_id AND p.code='name' AND t.code='salon_settings') THEN
  UPDATE __APP_SCHEMA__.salons SET name=NEW.value_string WHERE id=NEW.salon_id AND entity_id=NEW.entity_id;
 END IF;
 RETURN NULL;
END $$;

CREATE OR REPLACE FUNCTION __APP_SCHEMA__.guard_salon_registry() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, __APP_SCHEMA__ AS $$
BEGIN
 IF NEW.id<>OLD.id THEN RAISE EXCEPTION 'Salon identity is immutable' USING ERRCODE='23514'; END IF;
 IF pg_trigger_depth()=1 AND
  (NEW.name IS DISTINCT FROM OLD.name OR NEW.entity_id IS DISTINCT FROM OLD.entity_id) THEN
  RAISE EXCEPTION 'Salon name/entity are canonical metadata projections' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION __APP_SCHEMA__.shared_master_conflict(local_master_id bigint,start_text text,end_text text,exclude_id bigint DEFAULT NULL)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, __APP_SCHEMA__ AS $$
DECLARE shared_id bigint; sid bigint:=__APP_SCHEMA__.current_salon_id();
BEGIN
 IF sid IS NULL THEN RAISE EXCEPTION 'Salon context required' USING ERRCODE='42501'; END IF;
 SELECT shared_master_id INTO shared_id FROM __APP_SCHEMA__.masters WHERE salon_id=sid AND id=local_master_id;
 IF NOT FOUND THEN RAISE EXCEPTION 'Master not available in this salon' USING ERRCODE='42501'; END IF;
 IF exclude_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM __APP_SCHEMA__.bookings WHERE salon_id=sid AND id=exclude_id) THEN
  RAISE EXCEPTION 'Excluded booking not available in this salon' USING ERRCODE='42501';
 END IF;
 IF start_text::timestamptz>=end_text::timestamptz THEN
  RAISE EXCEPTION 'Invalid booking interval' USING ERRCODE='23514';
 END IF;
 RETURN EXISTS(SELECT 1 FROM __APP_SCHEMA__.shared_master_busy WHERE shared_master_id=shared_id
  AND booking_id IS DISTINCT FROM exclude_id
  AND start_utc<end_text::timestamptz AND end_utc>start_text::timestamptz);
END $$;

CREATE OR REPLACE FUNCTION __APP_SCHEMA__.protect_booking_overlap() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, __APP_SCHEMA__ AS $$
DECLARE shared_id bigint;
BEGIN
 IF NEW.salon_id IS DISTINCT FROM __APP_SCHEMA__.current_salon_id() THEN
  RAISE EXCEPTION 'Salon context required' USING ERRCODE='42501';
 END IF;
 IF NEW.status='confirmed' THEN
  IF current_setting('transaction_isolation')<>'read committed' THEN
   RAISE EXCEPTION 'Confirmed bookings require READ COMMITTED isolation'
    USING ERRCODE='0A000';
  END IF;
  PERFORM pg_advisory_xact_lock(706547229101);
  SELECT shared_master_id INTO STRICT shared_id FROM __APP_SCHEMA__.masters WHERE salon_id=NEW.salon_id AND id=NEW.master_id;
  IF EXISTS(SELECT 1 FROM __APP_SCHEMA__.shared_master_busy WHERE shared_master_id=shared_id
   AND booking_id IS DISTINCT FROM NEW.id AND start_utc<NEW.end_utc::timestamptz AND end_utc>NEW.start_utc::timestamptz)
  OR EXISTS(SELECT 1 FROM __APP_SCHEMA__.bookings b WHERE b.salon_id=NEW.salon_id AND b.status='confirmed'
   AND b.id IS DISTINCT FROM NEW.id AND b.start_utc::timestamptz<NEW.end_utc::timestamptz
   AND b.end_utc::timestamptz>NEW.start_utc::timestamptz
   AND (b.room_id=NEW.room_id OR (NEW.client_id IS NOT NULL AND b.client_id=NEW.client_id)
       OR b.phone_snapshot=NEW.phone_snapshot)) THEN
   RAISE EXCEPTION 'booking overlap' USING ERRCODE='23505';
  END IF;
 END IF;
 RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION __APP_SCHEMA__.sync_shared_master_busy() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, __APP_SCHEMA__ AS $$
DECLARE shared_id bigint;
BEGIN
 IF TG_OP='DELETE' THEN DELETE FROM __APP_SCHEMA__.shared_master_busy WHERE booking_id=OLD.id; RETURN OLD; END IF;
 IF NEW.status<>'confirmed' THEN DELETE FROM __APP_SCHEMA__.shared_master_busy WHERE booking_id=NEW.id; RETURN NEW; END IF;
 SELECT shared_master_id INTO STRICT shared_id FROM __APP_SCHEMA__.masters WHERE salon_id=NEW.salon_id AND id=NEW.master_id;
 INSERT INTO __APP_SCHEMA__.shared_master_busy(booking_id,shared_master_id,start_utc,end_utc)
 VALUES(NEW.id,shared_id,NEW.start_utc::timestamptz,NEW.end_utc::timestamptz)
 ON CONFLICT(booking_id) DO UPDATE SET shared_master_id=excluded.shared_master_id,
  start_utc=excluded.start_utc,end_utc=excluded.end_utc;
 RETURN NEW;
END $$;
