"""Transactional migration 4 for the shared, salon-scoped canonical store.

Call ``upgrade_shared(db)`` inside the migration's already-open transaction.
The first upgrade preserves legacy primary keys and rows, builds all canonical
entities before their references, installs guards, then enables/FORCEs RLS.
Any failure rolls back with the caller's transaction; there is no destructive
down migration. Repeated calls refresh functions/policies without rewriting data.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from database_namespace import relation_name

DDL = Path(__file__).with_name("shared_schema.sql")

# Static identifiers only. Never interpolate constructor/user input into SQL.
# Each legacy row is one canonical entity, including schedules and join rows.
MODELS = {
    "services": ("service", ("id",)),
    "masters": ("master", ("id",)),
    "rooms": ("room", ("id",)),
    "master_services": ("master_service", ("master_id", "service_id")),
    "room_services": ("room_service", ("room_id", "service_id")),
    "work_intervals": ("work_interval", ("id",)),
    "resource_blocks": ("resource_block", ("id",)),
    "clients": ("client", ("id",)),
    "bookings": ("booking", ("id",)),
    "booking_history": ("booking_history", ("id",)),
    "vk_dialogs": ("vk_dialog", ("vk_id",)),
    "inbound_events": ("inbound_event", ("event_id",)),
    "action_results": ("action_result", ("action_key",)),
    "message_outbox": ("message_outbox", ("id",)),
    "vk_outgoing_messages": ("vk_outgoing_message", ("id",)),
    "admin_audit_log": ("admin_audit", ("id",)),
}
SALON_TABLES = tuple(MODELS) + ("entity_types", "entities", "entity_parameters", "entity_parameter_values")
REFERENCES = {
    "master_id": ("masters", "id"), "service_id": ("services", "id"),
    "room_id": ("rooms", "id"), "client_id": ("clients", "id"),
    "booking_id": ("bookings", "id"), "prior_booking_id": ("bookings", "id"),
    "inbound_event_id": ("inbound_events", "event_id"),
}


def _columns(db, table):
    return db.execute("""SELECT a.attname AS name, a.attnotnull AS required,
        pg_catalog.format_type(a.atttypid,a.atttypmod) AS sql_type
        FROM pg_catalog.pg_attribute a WHERE a.attrelid=to_regclass(?)
        AND a.attnum>0 AND NOT a.attisdropped ORDER BY a.attnum""", (relation_name(db, table),)).fetchall()


def _rename_accounts(db):
    if db.execute("SELECT to_regclass('__APP_SCHEMA__.accounts')").fetchone()[0] is None:
        db.execute("ALTER TABLE __APP_SCHEMA__.admin_users RENAME TO accounts")
        db.execute("CREATE VIEW __APP_SCHEMA__.admin_users AS SELECT * FROM __APP_SCHEMA__.accounts")
    db.execute("DROP INDEX IF EXISTS __APP_SCHEMA__.one_active_admin")
    # Auth audit is global technical data, including preserved historical IDs.
    db.execute("""CREATE TABLE IF NOT EXISTS __APP_SCHEMA__.account_audit_log (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        actor text NOT NULL, action text NOT NULL, object_type text NOT NULL,
        object_id text, details_json text NOT NULL, created_at text NOT NULL)""")
    db.execute("""INSERT INTO __APP_SCHEMA__.account_audit_log
        (id,actor,action,object_type,object_id,details_json,created_at)
        SELECT id,actor,action,object_type,object_id,details_json,created_at
        FROM __APP_SCHEMA__.admin_audit_log WHERE action IN ('login','logout','provision_admin','admin_provisioned',
            'admin_login','admin_logout','admin_password_changed') OR object_type IN ('admin_user','admin_session')
        ON CONFLICT(id) DO NOTHING""")
    db.execute("""SELECT setval(pg_get_serial_sequence('__APP_SCHEMA__.account_audit_log','id'),
        COALESCE((SELECT max(id) FROM __APP_SCHEMA__.account_audit_log),1),
        EXISTS(SELECT 1 FROM __APP_SCHEMA__.account_audit_log))""")


def _drop_legacy_constraints(db):
    # Legacy global uniqueness and unscoped foreign keys are replaced, rather
    # than retained as a second, incompatible tenant policy.
    for table in MODELS:
        rows = db.execute("""SELECT conname,contype FROM pg_catalog.pg_constraint
            WHERE conrelid=to_regclass(?) AND contype IN ('f','u')""", (relation_name(db, table),)).fetchall()
        for row in rows:
            name = row["conname"].replace('"', '""')
            db.execute(f'ALTER TABLE __APP_SCHEMA__.{table} DROP CONSTRAINT "{name}"')
    # Natural/composite IDs can repeat in different salons. Numeric legacy IDs
    # remain globally unique, so no external/history identity is renumbered.
    for table in ("master_services", "room_services", "vk_dialogs", "inbound_events", "action_results"):
        name = db.execute("""SELECT conname FROM pg_catalog.pg_constraint
            WHERE conrelid=to_regclass(?) AND contype='p'""", (relation_name(db, table),)).fetchone()[0]
        db.execute(f'ALTER TABLE __APP_SCHEMA__.{table} DROP CONSTRAINT "{name}"')
        keys = ",".join(("salon_id",) + MODELS[table][1])
        db.execute(f"ALTER TABLE __APP_SCHEMA__.{table} ADD PRIMARY KEY({keys})")
    for index in ("services_name_ci", "masters_name_ci", "rooms_name_ci"):
        db.execute(f"DROP INDEX IF EXISTS __APP_SCHEMA__.{index}")


def _add_tenant_columns(db):
    for table in MODELS:
        db.execute(f"ALTER TABLE __APP_SCHEMA__.{table} ADD COLUMN IF NOT EXISTS salon_id bigint")
        db.execute(f"UPDATE __APP_SCHEMA__.{table} SET salon_id=1 WHERE salon_id IS NULL")
        db.execute(f"ALTER TABLE __APP_SCHEMA__.{table} ALTER COLUMN salon_id SET NOT NULL")
        db.execute(f"ALTER TABLE __APP_SCHEMA__.{table} ALTER COLUMN salon_id SET DEFAULT __APP_SCHEMA__.current_salon_id()")
        db.execute(f"ALTER TABLE __APP_SCHEMA__.{table} ADD COLUMN IF NOT EXISTS entity_id bigint")
    db.execute("ALTER TABLE __APP_SCHEMA__.masters ADD COLUMN IF NOT EXISTS shared_master_id bigint")
    db.execute("INSERT INTO __APP_SCHEMA__.shared_masters(id) SELECT id FROM __APP_SCHEMA__.masters ON CONFLICT DO NOTHING")
    db.execute("UPDATE __APP_SCHEMA__.masters SET shared_master_id=id WHERE shared_master_id IS NULL")
    db.execute("ALTER TABLE __APP_SCHEMA__.masters ALTER COLUMN shared_master_id SET NOT NULL")
    db.execute("""SELECT setval(pg_get_serial_sequence('__APP_SCHEMA__.shared_masters','id'),
        COALESCE((SELECT max(id) FROM __APP_SCHEMA__.shared_masters),1),EXISTS(SELECT 1 FROM __APP_SCHEMA__.shared_masters))""")


def _seed_metadata(db, starter):
    type_ids = {}
    for table, (code, _) in MODELS.items():
        type_ids[table] = db.execute("""INSERT INTO __APP_SCHEMA__.entity_types(salon_id,code,label,core,projection_table)
            VALUES(1,?,?,true,?) RETURNING id""", (code, code.replace("_", " "), table)).fetchone()[0]
    for table in MODELS:
        for col in _columns(db, table):
            name = col["name"]
            if name in ("id", "salon_id", "entity_id", "shared_master_id"):
                continue
            reference = REFERENCES.get(name)
            dtype = "reference" if reference else "integer" if col["sql_type"] in ("integer", "bigint") else "string"
            db.execute("""INSERT INTO __APP_SCHEMA__.entity_parameters
                (salon_id,entity_type_id,code,label,data_type,required,core,reference_type_id,reference_key)
                VALUES(1,?,?,?,?,?,true,?,?)""", (type_ids[table], name, name.replace("_", " "),
                    dtype, col["required"], type_ids[reference[0]] if reference else None,
                    reference[1] if reference else "id"))
    # Every type/entity exists before any reference value is materialized.
    for table, (_, keys) in MODELS.items():
        key_expr = "jsonb_build_object(" + ",".join(f"'{key}',p.{key}" for key in keys) + ")"
        db.execute(f"""INSERT INTO __APP_SCHEMA__.entities(salon_id,entity_type_id,projection_key)
            SELECT salon_id,?,{key_expr} FROM __APP_SCHEMA__.{table} p""", (type_ids[table],))
        db.execute(f"""UPDATE __APP_SCHEMA__.{table} p SET entity_id=e.id FROM __APP_SCHEMA__.entities e
            WHERE e.salon_id=p.salon_id AND e.entity_type_id=? AND e.projection_key={key_expr}""", (type_ids[table],))
    # Invoke the same synchronization function used by future command writes.
    for table in MODELS:
        db.execute(f"CREATE TRIGGER canonical_backfill AFTER UPDATE ON __APP_SCHEMA__.{table} FOR EACH ROW EXECUTE FUNCTION __APP_SCHEMA__.sync_projection_values()")
        db.execute(f"UPDATE __APP_SCHEMA__.{table} SET entity_id=entity_id")
        db.execute(f"DROP TRIGGER canonical_backfill ON __APP_SCHEMA__.{table}")
    settings_type = db.execute("""INSERT INTO __APP_SCHEMA__.entity_types(salon_id,code,label,core)
        VALUES(1,'salon_settings','Salon settings',true) RETURNING id""").fetchone()[0]
    settings_entity = db.execute("""INSERT INTO __APP_SCHEMA__.entities(salon_id,entity_type_id,projection_key)
        VALUES(1,?, '{"id":1}') RETURNING id""", (settings_type,)).fetchone()[0]
    values = {"name": starter["label"], **starter["policy"]}
    for key, value in values.items():
        dtype = "boolean" if type(value) is bool else "integer" if type(value) is int else "string"
        param = db.execute("""INSERT INTO __APP_SCHEMA__.entity_parameters
            (salon_id,entity_type_id,code,label,data_type,required,core)
            VALUES(1,?,?,?,?,true,true) RETURNING id""", (settings_type, key, key.replace("_", " "), dtype)).fetchone()[0]
        column = {"boolean": "value_boolean", "integer": "value_integer", "string": "value_string"}[dtype]
        db.execute(f"""INSERT INTO __APP_SCHEMA__.entity_parameter_values(salon_id,entity_id,parameter_id,entity_type_id,{column})
            VALUES(1,?,?,?,?)""", (settings_entity, param, settings_type, value))
    db.execute("UPDATE __APP_SCHEMA__.salons SET entity_id=? WHERE id=1", (settings_entity,))
    db.execute("""INSERT INTO __APP_SCHEMA__.core_entity_templates(code,label,projection_table,parameters,defaults)
        SELECT t.code,t.label,t.projection_table,
          (SELECT jsonb_agg(jsonb_build_object('code',p.code,'label',p.label,'data_type',p.data_type,
              'required',p.required,'reference_code',r.code,'reference_key',p.reference_key) ORDER BY p.id)
           FROM __APP_SCHEMA__.entity_parameters p LEFT JOIN __APP_SCHEMA__.entity_types r
             ON r.salon_id=p.salon_id AND r.id=p.reference_type_id
           WHERE p.salon_id=t.salon_id AND p.entity_type_id=t.id),
          CASE WHEN t.code='salon_settings' THEN ?::jsonb ELSE '{}'::jsonb END
        FROM __APP_SCHEMA__.entity_types t WHERE t.salon_id=1 AND t.core""", (json.dumps(values),))


def _scoped_constraints(db):
    for table, (_, keys) in MODELS.items():
        db.execute(f"ALTER TABLE __APP_SCHEMA__.{table} ALTER COLUMN entity_id SET NOT NULL")
        db.execute(f"ALTER TABLE __APP_SCHEMA__.{table} ADD CONSTRAINT {table}_salon_fk FOREIGN KEY(salon_id) REFERENCES __APP_SCHEMA__.salons(id)")
        db.execute(f"ALTER TABLE __APP_SCHEMA__.{table} ADD CONSTRAINT {table}_entity_unique UNIQUE(entity_id)")
        db.execute(f"ALTER TABLE __APP_SCHEMA__.{table} ADD CONSTRAINT {table}_entity_fk FOREIGN KEY(salon_id,entity_id) REFERENCES __APP_SCHEMA__.entities(salon_id,id)")
        if keys == ("id",):
            db.execute(f"ALTER TABLE __APP_SCHEMA__.{table} ADD CONSTRAINT {table}_salon_id_unique UNIQUE(salon_id,id)")
        for col in _columns(db, table):
            reference = REFERENCES.get(col["name"])
            if reference:
                target, key = reference
                db.execute(f"""ALTER TABLE __APP_SCHEMA__.{table} ADD CONSTRAINT {table}_{col['name']}_salon_fk
                    FOREIGN KEY(salon_id,{col['name']}) REFERENCES __APP_SCHEMA__.{target}(salon_id,{key})""")
    db.execute("ALTER TABLE __APP_SCHEMA__.masters ADD CONSTRAINT masters_shared_identity_fk FOREIGN KEY(shared_master_id) REFERENCES __APP_SCHEMA__.shared_masters(id)")
    db.execute("ALTER TABLE __APP_SCHEMA__.masters ADD CONSTRAINT masters_one_profile_per_salon UNIQUE(salon_id,shared_master_id)")
    db.execute("ALTER TABLE __APP_SCHEMA__.salons ADD CONSTRAINT salons_entity_fk FOREIGN KEY(id,entity_id) REFERENCES __APP_SCHEMA__.entities(salon_id,id)")
    for table in ("bookings", "resource_blocks"):
        db.execute(f"""ALTER TABLE __APP_SCHEMA__.{table} ADD CONSTRAINT {table}_utc_interval_valid
            CHECK(start_utc::timestamptz<end_utc::timestamptz)""")
    for table in ("services", "masters", "rooms"):
        db.execute(f"CREATE UNIQUE INDEX {table}_salon_name_ci ON __APP_SCHEMA__.{table}(salon_id,lower(btrim(name)))")
    for table, columns in (("clients", "vk_id"), ("message_outbox", "booking_id,event_kind"),
                            ("vk_outgoing_messages", "dedupe_key"), ("vk_outgoing_messages", "random_id")):
        name = table + "_salon_" + columns.replace(",", "_") + "_unique"
        db.execute(f"CREATE UNIQUE INDEX {name} ON __APP_SCHEMA__.{table}(salon_id,{columns})")


def _preserve_identity_sequences(db):
    for table in tuple(t for t, (_, keys) in MODELS.items() if keys == ("id",)) + ("accounts",):
        # Preserve a sequence already ahead of live rows, while repairing old
        # explicit-ID seeds whose identity sequence was never advanced.
        db.execute(f"""SELECT setval(pg_get_serial_sequence('__APP_SCHEMA__.{table}','id'),
            GREATEST(COALESCE((SELECT max(id) FROM __APP_SCHEMA__.{table}),1),
              COALESCE(pg_sequence_last_value(pg_get_serial_sequence('__APP_SCHEMA__.{table}','id')::regclass),1)),
            EXISTS(SELECT 1 FROM __APP_SCHEMA__.{table}) OR
              pg_sequence_last_value(pg_get_serial_sequence('__APP_SCHEMA__.{table}','id')::regclass) IS NOT NULL)""")


def _install_triggers(db):
    db.execute("DROP TRIGGER IF EXISTS salon_metadata_initialize ON __APP_SCHEMA__.salons")
    db.execute("CREATE TRIGGER salon_metadata_initialize AFTER INSERT ON __APP_SCHEMA__.salons FOR EACH ROW EXECUTE FUNCTION __APP_SCHEMA__.initialize_salon_metadata()")
    db.execute("DROP TRIGGER IF EXISTS salon_registry_guard ON __APP_SCHEMA__.salons")
    db.execute("CREATE TRIGGER salon_registry_guard BEFORE UPDATE ON __APP_SCHEMA__.salons FOR EACH ROW EXECUTE FUNCTION __APP_SCHEMA__.guard_salon_registry()")
    for table, (_, keys) in MODELS.items():
        code = MODELS[table][0]
        for name in ("canonical_entity_before", "canonical_values_after", "canonical_ignored_cleanup"):
            db.execute(f"DROP TRIGGER IF EXISTS {name} ON __APP_SCHEMA__.{table}")
        db.execute(f"""CREATE TRIGGER canonical_entity_before BEFORE INSERT OR UPDATE ON __APP_SCHEMA__.{table}
            FOR EACH ROW EXECUTE FUNCTION __APP_SCHEMA__.projection_entity_before('{code}','{','.join(keys)}')""")
        db.execute(f"""CREATE TRIGGER canonical_values_after AFTER INSERT OR UPDATE OR DELETE ON __APP_SCHEMA__.{table}
            FOR EACH ROW EXECUTE FUNCTION __APP_SCHEMA__.sync_projection_values()""")
        db.execute(f"""CREATE TRIGGER canonical_ignored_cleanup AFTER INSERT ON __APP_SCHEMA__.{table}
            FOR EACH STATEMENT EXECUTE FUNCTION __APP_SCHEMA__.prune_ignored_projection_entities('{code}')""")
    for table, name, function in (("entity_types", "metadata_guard", "guard_metadata"),
            ("entity_parameters", "metadata_guard", "guard_metadata"),
            ("entities", "entity_guard", "guard_entity"),
            ("entity_parameter_values", "entity_value_guard", "guard_entity_value")):
        db.execute(f"DROP TRIGGER IF EXISTS {name} ON __APP_SCHEMA__.{table}")
        db.execute(f"CREATE TRIGGER {name} BEFORE INSERT OR UPDATE OR DELETE ON __APP_SCHEMA__.{table} FOR EACH ROW EXECUTE FUNCTION __APP_SCHEMA__.{function}()")
    for table in ("entities", "entity_parameter_values"):
        db.execute(f"DROP TRIGGER IF EXISTS required_values ON __APP_SCHEMA__.{table}")
        db.execute(f"""CREATE CONSTRAINT TRIGGER required_values AFTER INSERT OR UPDATE OR DELETE ON __APP_SCHEMA__.{table}
            DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION __APP_SCHEMA__.check_required_entity_values()""")
    db.execute("DROP TRIGGER IF EXISTS value_version ON __APP_SCHEMA__.entity_parameter_values")
    db.execute("""CREATE TRIGGER value_version AFTER INSERT OR UPDATE OR DELETE ON __APP_SCHEMA__.entity_parameter_values
        FOR EACH ROW EXECUTE FUNCTION __APP_SCHEMA__.bump_entity_value_version()""")
    db.execute("DROP TRIGGER IF EXISTS salon_name_projection ON __APP_SCHEMA__.entity_parameter_values")
    db.execute("""CREATE TRIGGER salon_name_projection AFTER INSERT OR UPDATE ON __APP_SCHEMA__.entity_parameter_values
        FOR EACH ROW EXECUTE FUNCTION __APP_SCHEMA__.sync_salon_name()""")
    db.execute("DROP TRIGGER IF EXISTS booking_overlap_guard ON __APP_SCHEMA__.bookings")
    db.execute("""CREATE TRIGGER booking_overlap_guard BEFORE INSERT OR UPDATE ON __APP_SCHEMA__.bookings
        FOR EACH ROW EXECUTE FUNCTION __APP_SCHEMA__.protect_booking_overlap()""")
    db.execute("DROP TRIGGER IF EXISTS shared_busy_projection ON __APP_SCHEMA__.bookings")
    db.execute("""CREATE TRIGGER shared_busy_projection AFTER INSERT OR UPDATE OR DELETE ON __APP_SCHEMA__.bookings
        FOR EACH ROW EXECUTE FUNCTION __APP_SCHEMA__.sync_shared_master_busy()""")


def _install_rls(db):
    for table in SALON_TABLES:
        db.execute(f"ALTER TABLE __APP_SCHEMA__.{table} ENABLE ROW LEVEL SECURITY")
        db.execute(f"ALTER TABLE __APP_SCHEMA__.{table} FORCE ROW LEVEL SECURITY")
        db.execute(f"DROP POLICY IF EXISTS salon_isolation ON __APP_SCHEMA__.{table}")
        db.execute(f"""CREATE POLICY salon_isolation ON __APP_SCHEMA__.{table}
            USING(salon_id=__APP_SCHEMA__.current_salon_id()) WITH CHECK(salon_id=__APP_SCHEMA__.current_salon_id())""")


def upgrade_shared(db):
    """Upgrade v3 once and refresh the version-4 guards on subsequent calls."""
    applied = db.execute("SELECT 1 FROM __APP_SCHEMA__.schema_migrations WHERE version=4").fetchone() is not None
    if not applied:
        starter = json.loads(Path(__file__).with_name("starter_data.json").read_text(encoding="utf-8"))
        if os.environ.get("SALON_POLICY_JSON"):
            starter = {**starter, "policy": json.loads(os.environ["SALON_POLICY_JSON"])}
        _validate_shared_policy(starter["policy"])
        _rename_accounts(db)
        # Replace the legacy function only after detaching its trigger. Otherwise
        # the backfill UPDATE would invoke the new tenant guard before context/
        # salon_id exists, making an existing-data upgrade fail.
        db.execute("DROP TRIGGER IF EXISTS booking_overlap_guard ON __APP_SCHEMA__.bookings")
        db.execute(DDL.read_text(encoding="utf-8"))
        db.execute("INSERT INTO __APP_SCHEMA__.salons(id,name) VALUES(1,?) ON CONFLICT DO NOTHING", (starter["label"],))
        db.execute("SELECT setval(pg_get_serial_sequence('__APP_SCHEMA__.salons','id'),GREATEST((SELECT max(id) FROM __APP_SCHEMA__.salons),1),true)")
        _add_tenant_columns(db)
        _drop_legacy_constraints(db)
        # Old booking trigger is global and would reject unrelated salon phones.
        db.execute("DROP TRIGGER IF EXISTS booking_overlap_guard ON __APP_SCHEMA__.bookings")
        _seed_metadata(db, starter)
        _scoped_constraints(db)
        _preserve_identity_sequences(db)
        db.execute("""INSERT INTO __APP_SCHEMA__.salon_memberships(salon_id,user_id,role,active)
            SELECT 1,id,role,active FROM __APP_SCHEMA__.accounts ON CONFLICT DO NOTHING""")
        db.execute("""INSERT INTO __APP_SCHEMA__.shared_master_busy(booking_id,shared_master_id,start_utc,end_utc)
            SELECT b.id,m.shared_master_id,b.start_utc::timestamptz,b.end_utc::timestamptz
            FROM __APP_SCHEMA__.bookings b JOIN __APP_SCHEMA__.masters m ON m.salon_id=b.salon_id AND m.id=b.master_id
            WHERE b.status='confirmed' ON CONFLICT(booking_id) DO NOTHING""")
        db.execute("INSERT INTO __APP_SCHEMA__.schema_migrations(version,applied_at) VALUES(4,to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"'))")
    else:
        db.execute(DDL.read_text(encoding="utf-8"))
        db.execute("DROP INDEX IF EXISTS __APP_SCHEMA__.one_active_admin")
    _install_triggers(db)
    _install_rls(db)


def _validate_shared_policy(policy):
    from booking_core import validate_policy
    if not isinstance(policy, dict):
        raise ValueError("Salon policy is required")
    validate_policy(policy)
    if policy.get("buffer_minutes") != 0 or policy.get("allow_parallel_client_bookings") is not False:
        raise ValueError("This shared booking core requires buffer_minutes=0 and allow_parallel_client_bookings=false")


def provision_salon(db, name, policy):
    """Technical owner provisioning inside an existing transaction, not public registration.

    ``policy`` must be an approved complete booking policy. The caller controls
    account/membership authorization and commits the new salon atomically.
    """
    if not isinstance(name, str) or not 1 <= len(name.strip()) <= 200:
        raise ValueError("Salon name is required")
    _validate_shared_policy(policy)
    previous = db.execute("SELECT current_setting('app.provision_policy',true)").fetchone()[0]
    try:
        db.execute("SELECT set_config('app.provision_policy',?,true)", (json.dumps(policy),))
        return db.execute("INSERT INTO __APP_SCHEMA__.salons(name) VALUES(?) RETURNING id", (name.strip(),)).fetchone()[0]
    finally:
        db.execute("SELECT set_config('app.provision_policy',?,true)", (previous or "",))
